server:
  port: 8082

spring:
  application:
    name: bank-b-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

bank:
  code: BANK_B
  data:
    clients-file: data/clients_B.json
    accounts-file: data/accounts_B.json
    transactions-log: data/transactions_B.log
    backup-accounts-file: data/backup_accounts_B.json
