server:
  port: 8081

spring:
  application:
    name: bank-a-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

bank:
  code: BANK_A
  data:
    clients-file: data/clients_A.json
    accounts-file: data/accounts_A.json
    transactions-log: data/transactions_A.log
    backup-accounts-file: data/backup_accounts_A.json
